# Generated by Django 6.0 on 2025-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pics/111.png', upload_to='profile_pics'),
        ),
    ]
