# Generated by Django 6.0 on 2026-01-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='foot_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='head_content',
            field=models.TextField(blank=True),
        ),
    ]
